
services:
  python:
    image: python:3.10-slim
    container_name: pnp_python
    working_dir: /app
    ports:
      - "6515:6515" 
    volumes:
      - ./python:/app
    command: /bin/bash -c "pip install --no-cache-dir -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 6515 --reload"

  nodejs:
    image: node:latest
    container_name: pnp_nodejs
    working_dir: /app
    ports:
      - "6514:3000"
    volumes:
      - ./nodejs:/app
    command: /bin/bash -c "npm install && npm i -g nodemon && nodemon"